### ISSUE TITLE
Internal Server Error upon different language input

### ISSUE THREAD

**Issue by AR621** [AR621/Summ3r-y#9]
User view:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
Server side log:
```
UnicodeEncodeError: 'charmap' codec can't encode character '\u0144' in position 5: character maps to <undefined>
```
The uploaded file was in polish lang. so the crash is caused most likely due to error while processing the special characters in polish lang.

**Comment by colonelWalterKurtz** [comment]
There was a problem with encoding. Txt files were written in "UTF-8", but the read file function was using "ASCII".
